on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: read

name: Prerelease

jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
          # optional. customize path to release-please-config-prerelease.json
          config-file: .github/release-please-config-prerelease.json
          # optional. customize path to .release-please-manifest-prerelease.json
          manifest-file: .github/.release-please-manifest-prerelease.json

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"
